modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="coc"
version="1.0.0"
displayName="Caves of Cobalt"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="rmsandegs"
description='''
Complete remaking of the underground
'''

[[dependencies.coc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




